package com.utradia.catalogueappv2.constants

interface ApiConstants {
    companion object {
        const val STATUS_SUCCESS_0 = 0
        const val STATUS_SUCCESS_400 = 400
        const val STATUS_SUCCESS_300 = 300
        const val STATUS_SUCCESS_1 = 1
        const val BASE_URL = "http://35.163.109.148"
        const val CONTROLLER = "/index.php/api"
        //http://35.163.109.148/index.php/api/login
        const val LOGIN = "$CONTROLLER/login"
        const val GET_COUNTRIES = "$CONTROLLER/get_countries"
        const val SIGN_UP = "$CONTROLLER/signup"
        const val UPDATE_USER = "$CONTROLLER/update_users"
        const val UPDATE_EMAIL = "$CONTROLLER/update_email"
        const val PROFILE = "$CONTROLLER/profile"
        const val GET_SHOP_LISTING = "$CONTROLLER/get_shop_listing"
        const val GET_EVENTS = "$CONTROLLER/get_events"
        const val GET_EVENT_DETAILS = "$CONTROLLER/get_event_details"
        const val GOING_EVENT = "$CONTROLLER/going_to_event"
        const val UNGOING_EVENT = "$CONTROLLER/ungoing_to_event"
        const val HOMESCREEN = "$CONTROLLER/homescreen"
        const val GET_TWO_LEVEL_CATEGORIES = "$CONTROLLER/get_two_level_categories"
        const val GET_OFFERS = "$CONTROLLER/get_offers"
        const val GET_OFFER_DETAILS = "$CONTROLLER/get_offer_details"
        const val GET_SUB_CATEGORIES_BY_PARENT_ID = "$CONTROLLER/get_sub_categories_by_parent_id"
        const val ADD_FAVOURITE = "$CONTROLLER/add_favourite"
        const val REMOVE_FAVOURITE = "$CONTROLLER/remove_favourite"
        const val FAVOURITE_LIST = "$CONTROLLER/fav_list"
        const val ADD_TO_CART = "$CONTROLLER/add_to_cart"
        const val GET_CLIENT_DATA = "$CONTROLLER/get_client_data"
        const val GET_CLIENT_OFFERS = "$CONTROLLER/get_offers_by_client_and_cat_id"
        const val FOLLOW_CLIENT = "$CONTROLLER/follow_client"
        const val UNFOLLOW_CLIENT = "$CONTROLLER/unfollow_client"
        const val GET_OFFER_BY_CATEGORY_ID = "$CONTROLLER/get_offers_by_category_id"
        const val FLASH_SALES = "$CONTROLLER/flash_sales"
        const val GET_MOST_POPULAR_ITEMS = "$CONTROLLER/most_popular_items"
        const val GET_CART = "$CONTROLLER/cart_list"
        const val REMOVE_ITEM_FROM_CART = "$CONTROLLER/remove_item_from_cart"
        const val UPDATE_QUANTITY = "$CONTROLLER/update_quantity"
        const val MOVE_TO_WISHLIST = "$CONTROLLER/move_to_wishlist"
        const val RECOMMENDED_ITEMS = "$CONTROLLER/recommended_items"
        const val ADD_ADDRESS = "$CONTROLLER/add_address"
        const val GET_REGIONS = "$CONTROLLER/get_regions"
        const val GET_CITIES_BY_REGION = "$CONTROLLER/get_cities_by_region_id"
        const val UPDATE_ADDRESS = "$CONTROLLER/update_address"
        const val GET_ADDRESS = "$CONTROLLER/get_address"
        const val DELETE_ADDRESS = "$CONTROLLER/delete_address"
        const val GET_ADDRESS_DETAILS = "$CONTROLLER/get_address_details"
        const val MAKE_DEFAULT_ADDRESS = "$CONTROLLER/make_default_address"
        const val GET_NOTIFICATION_SETTINGS = "$CONTROLLER/get_notification_settings"
        const val UPDATE_NOTIFICATION_SETTINGS = "$CONTROLLER/update_notification_settings"
        const val CHECKOUT_DATA = "$CONTROLLER/checkout_data"
        const val APPLY_PROMOCODE = "$CONTROLLER/apply_promocode"
        const val PLACE_ORDER = "$CONTROLLER/place_order"
        const val GET_SHIPMENT_PRICES = "$CONTROLLER/get_shipment_prices"
        const val BUY_NOW_CART = "$CONTROLLER/buy_now_cart"
        const val BUY_NOW_CHECKOUT_DATA = "$CONTROLLER/buy_now_checkout_data"
        const val ORDER_LIST = "$CONTROLLER/order_list"
        const val ORDER_DETAIL = "$CONTROLLER/order_details"
        const val PRODUCT_RATE_REVIEW = "$CONTROLLER/product_review_and_rating"
        const val RATE_REVIEW_LIST= "$CONTROLLER/get_rating_and_reviews"
        const val CANCEL_ORDER= "$CONTROLLER/cancel_order"
        const val UPLOAD_IMAGE= "$CONTROLLER/profile_pic"
        const val GET_BRAND_LIST= "$CONTROLLER/get_brand_listing"
        const val GET_CATEGORY_LIST= "$CONTROLLER/get_filter_category_list"
        const val SEARCH_OFFERS= "$CONTROLLER/get_keywords_list"
        const val SEARCH_OFFER_LIST= "$CONTROLLER/list_offers"
        const val SEARCH_OFFER_BY_ID= "$CONTROLLER/search_offers_by_category_id"
        const val ORDER_PAYNOW= "$CONTROLLER/pay_now"
        const val ADD_DEVICE= "$CONTROLLER/add_device"
        const val LOGOUT= "$CONTROLLER/logout"
        const val NOTIFICATION_LIST= "$CONTROLLER/get_notifications"
        const val SHOP_CATALOGUE= "$CONTROLLER/get_catalogues"
        const val SHOP_CATALOGUE_ITEM= "$CONTROLLER/get_catalogue_items"
    }


}
